"""change models

Revision ID: 1efad4e603fa
Revises: 88304650d8a9
Create Date: 2022-08-09 21:48:59.993006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efad4e603fa'
down_revision = '88304650d8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_for_order', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('products_for_order', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_for_order', 'quantity')
    op.drop_column('products_for_order', 'id')
    # ### end Alembic commands ###
