"""change

Revision ID: 6b9170de22c6
Revises: 1efad4e603fa
Create Date: 2022-08-09 23:24:22.602003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9170de22c6'
down_revision = '1efad4e603fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_for_order', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_for_order', 'total_price')
    # ### end Alembic commands ###
